"""Crear modulo de pagos

Revision ID: 682deeaf810b
Revises: 45e85a1a0640
Create Date: 2026-09-26 23:07:06.833315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682deeaf810b'
down_revision = '45e85a1a0640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('metodo', sa.String(length=50), nullable=True),
    sa.Column('id_transaccion', sa.String(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referencia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    # ### end Alembic commands ###
