"""Crear personalizaciones y configurar tarjeta

Revision ID: a3bba3eebe4e
Revises: b7e91c8d4a12
Create Date: 2026-09-24 00:28:02.159277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3bba3eebe4e'
down_revision = 'b7e91c8d4a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('grabado', sa.String(length=500), nullable=True),
    sa.Column('mensaje', sa.String(length=1000), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos_personalizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personalizacion_id', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personalizacion_id'], ['personalizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opciones_personalizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personalizacion_id', sa.Integer(), nullable=False),
    sa.Column('opcion_producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opcion_producto_id'], ['opciones_productos.id'], ),
    sa.ForeignKeyConstraint(['personalizacion_id'], ['personalizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permite_tarjeta', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('max_caracteres_tarjeta', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('max_caracteres_tarjeta')
        batch_op.drop_column('permite_tarjeta')

    op.drop_table('opciones_personalizaciones')
    op.drop_table('fotos_personalizaciones')
    op.drop_table('personalizaciones')
    # ### end Alembic commands ###
