"""Actualizar modelo de productos

Revision ID: e340bb54f575
Revises: f4fa52df6a92
Create Date: 2026-09-11 01:57:37.022714

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'e340bb54f575'
down_revision = 'f4fa52df6a92'
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###

    inspector = sa.inspect(op.get_bind())

    if not inspector.has_table('imagenes_productos'):

        op.create_table(
            'imagenes_productos',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('producto_id', sa.Integer(), nullable=False),
            sa.Column('url_imagen', sa.String(length=500), nullable=False),
            sa.Column('orden', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ['producto_id'],
                ['productos.id']
            ),
            sa.PrimaryKeyConstraint('id')
        )

    if not inspector.has_table('opciones_productos'):

        op.create_table(
            'opciones_productos',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('producto_id', sa.Integer(), nullable=False),
            sa.Column('tipo', sa.String(length=50), nullable=False),
            sa.Column('valor', sa.String(length=100), nullable=False),
            sa.ForeignKeyConstraint(
                ['producto_id'],
                ['productos.id']
            ),
            sa.PrimaryKeyConstraint('id')
        )

    # Eliminamos las tablas antiguas.
    # Las reconstruiremos posteriormente.
    op.drop_table('pedido_items')
    op.drop_table('accesorios')
    op.drop_table('pedidos')

    with op.batch_alter_table(
        'productos',
        schema=None
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                'stock',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        batch_op.add_column(
            sa.Column(
                'disponible',
                sa.Boolean(),
                nullable=False,
                server_default='1'
            )
        )

        batch_op.add_column(
            sa.Column(
                'categoria',
                sa.String(length=100),
                nullable=False,
                server_default='General'
            )
        )

        batch_op.add_column(
            sa.Column(
                'min_fotos',
                sa.Integer(),
                nullable=False,
                server_default='1'
            )
        )

        batch_op.add_column(
            sa.Column(
                'max_fotos',
                sa.Integer(),
                nullable=False,
                server_default='1'
            )
        )

        batch_op.add_column(
            sa.Column(
                'precio_grabado',
                sa.Numeric(
                    precision=10,
                    scale=2
                ),
                nullable=False,
                server_default='0'
            )
        )

        batch_op.add_column(
            sa.Column(
                'fecha_creacion',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.now()
            )
        )

        batch_op.alter_column(
            'precio',
            existing_type=mysql.FLOAT(),
            type_=sa.Numeric(
                precision=10,
                scale=2
            ),
            existing_nullable=False
        )

        batch_op.alter_column(
            'permite_grabado',
            existing_type=mysql.TINYINT(
                display_width=1
            ),
            nullable=False
        )

        batch_op.drop_column('imagen')
        batch_op.drop_column('colores')
        batch_op.drop_column('precio_extra_grabado')
        batch_op.drop_column('activo')
        batch_op.drop_column('permite_tarjeta')

    # ### end Alembic commands ###


def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table(
        'productos',
        schema=None
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                'permite_tarjeta',
                mysql.TINYINT(display_width=1),
                autoincrement=False,
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'activo',
                mysql.TINYINT(display_width=1),
                autoincrement=False,
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'precio_extra_grabado',
                mysql.FLOAT(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'colores',
                mysql.VARCHAR(length=255),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'imagen',
                mysql.VARCHAR(length=255),
                nullable=False
            )
        )

        batch_op.alter_column(
            'permite_grabado',
            existing_type=mysql.TINYINT(display_width=1),
            nullable=True
        )

        batch_op.alter_column(
            'precio',
            existing_type=sa.Numeric(
                precision=10,
                scale=2
            ),
            type_=mysql.FLOAT(),
            existing_nullable=False
        )

        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('precio_grabado')
        batch_op.drop_column('max_fotos')
        batch_op.drop_column('min_fotos')
        batch_op.drop_column('categoria')
        batch_op.drop_column('disponible')
        batch_op.drop_column('stock')

    op.create_table(
        'accesorios',
        sa.Column(
            'id',
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False
        ),
        sa.Column(
            'nombre',
            mysql.VARCHAR(length=100),
            nullable=False
        ),
        sa.Column(
            'descripcion',
            mysql.TEXT(),
            nullable=False
        ),
        sa.Column(
            'precio_extra',
            mysql.FLOAT(),
            nullable=True
        ),
        sa.Column(
            'activo',
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True
        ),
        sa.Column(
            'producto_id',
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['producto_id'],
            ['productos.id'],
            name=op.f('accesorios_ibfk_1')
        ),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_general_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )

    op.create_table(
        'pedidos',
        sa.Column(
            'id',
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False
        ),
        sa.Column(
            'usuario_id',
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'total',
            mysql.FLOAT(),
            nullable=False
        ),
        sa.Column(
            'direccion_envio',
            mysql.VARCHAR(length=255),
            nullable=False
        ),
        sa.Column(
            'estado',
            mysql.VARCHAR(length=50),
            nullable=True
        ),
        sa.Column(
            'fecha_creacion',
            mysql.DATETIME(),
            nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['usuario_id'],
            ['usuarios.id'],
            name=op.f('pedidos_ibfk_1')
        ),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_general_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )

    op.create_table(
        'pedido_items',
        sa.Column(
            'id',
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False
        ),
        sa.Column(
            'pedido_id',
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'producto_id',
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'accesorio_id',
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True
        ),
        sa.Column(
            'color',
            mysql.VARCHAR(length=100),
            nullable=True
        ),
        sa.Column(
            'grabado',
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True
        ),
        sa.Column(
            'texto_grabado',
            mysql.VARCHAR(length=255),
            nullable=True
        ),
        sa.Column(
            'tarjeta',
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True
        ),
        sa.Column(
            'mensaje_tarjeta',
            mysql.VARCHAR(length=255),
            nullable=True
        ),
        sa.Column(
            'subtotal',
            mysql.FLOAT(),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['accesorio_id'],
            ['accesorios.id'],
            name=op.f('pedido_items_ibfk_1')
        ),
        sa.ForeignKeyConstraint(
            ['pedido_id'],
            ['pedidos.id'],
            name=op.f('pedido_items_ibfk_2')
        ),
        sa.ForeignKeyConstraint(
            ['producto_id'],
            ['productos.id'],
            name=op.f('pedido_items_ibfk_3')
        ),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_general_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )

    op.drop_table('opciones_productos')
    op.drop_table('imagenes_productos')

    # ### end Alembic commands ###
